site_name: The Free Realms Wiki
site_url: https://northernscott.github.io/

repo_url: https://github.com/NorthernScott/thefreerealms/
repo_name: Github
edit_uri: main/docs/

theme:
    name: 'material'
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep orange
      toggle: 
        icon: material/toggle-switch
        name: Switch to light mode

    font: 
      text: IBM Plex Serif
      code: IBM Plex Mono
    favicon: assets/images/favicon.png
    features:
      - header.autohide
    language: en-CA
    extra:
      copyright: Copyright &copy; 2022 S. Drennan

# Extensions
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 
  - mermaid2

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
